name: Checkmarx One Scan
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: Checkmarx/Java-WebApp
          cx_tenant: beta_nova8
          base_uri: https://eu.ast.checkmarx.net 
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: >-
            --scan-types sast
            --filter severity "High"
            --threshold sast-high=1
            --sast-preset-name "High"
          
